[ env ]
TERM = "xterm-256color"

[window]
opacity = 1

padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
#normal.family = "MesloLGS NF"
normal.family = "Monocraft"
bold.family = "Monocraft"
italic.family = "Monocraft"
bold_italic.family = "Monocraft"

# normal.family = "JetBrainsMono Nerd Font"
# bold.family = "JetBrainsMono Nerd Font"
# italic.family = "JetBrainsMono Nerd Font"
# bold_italic.family = "JetBrainsMono Nerd Font"


#regular
size = 10

[general]
import = [
    "~/.config/alacritty/themes/blackout.toml"
]
#for video
# size = 35.0
